apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
     labels:
       app: myapp
    spec:
      containers:
        - name: springboot-container  
          image: saurabhgore70/springboot-app:v2
